// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCajVaQQtz0VcePRQOd__ubd2A5HyMlfy0',
    appId: '1:206011392773:web:5b5b1eb553d54d15660d6c',
    messagingSenderId: '206011392773',
    projectId: 'lakesebu-dcd8c',
    authDomain: 'lakesebu-dcd8c.firebaseapp.com',
    storageBucket: 'lakesebu-dcd8c.firebasestorage.app',
    measurementId: 'G-BXSNF48PD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOF8e2qDIx9ViA0pgq9DjplY_SmGiDXA',
    appId: '1:206011392773:android:78d4a5dc0a7928a1660d6c',
    messagingSenderId: '206011392773',
    projectId: 'lakesebu-dcd8c',
    storageBucket: 'lakesebu-dcd8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtft6mZTpUMZStkSRYMc2OogQ2CZRxWvI',
    appId: '1:206011392773:ios:8220dc5a1299e82c660d6c',
    messagingSenderId: '206011392773',
    projectId: 'lakesebu-dcd8c',
    storageBucket: 'lakesebu-dcd8c.firebasestorage.app',
    iosBundleId: 'com.example.lakeSebu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtft6mZTpUMZStkSRYMc2OogQ2CZRxWvI',
    appId: '1:206011392773:ios:8220dc5a1299e82c660d6c',
    messagingSenderId: '206011392773',
    projectId: 'lakesebu-dcd8c',
    storageBucket: 'lakesebu-dcd8c.firebasestorage.app',
    iosBundleId: 'com.example.lakeSebu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCajVaQQtz0VcePRQOd__ubd2A5HyMlfy0',
    appId: '1:206011392773:web:8d99bd2e9a529d6e660d6c',
    messagingSenderId: '206011392773',
    projectId: 'lakesebu-dcd8c',
    authDomain: 'lakesebu-dcd8c.firebaseapp.com',
    storageBucket: 'lakesebu-dcd8c.firebasestorage.app',
    measurementId: 'G-TJ2S8LQ886',
  );
}
